#!/bin/sh
# emile@guntari.com

#-----------------------------------------------------------------------------#  
#                                                                             #
#                                              ____                           #
#     `````````:'       .'.       `````````:' |            |..          |     #
#           ..'       .''```.           ..'   |______      |  ``..      |     #
#       ..''        .'       `.     ..''      |            |      ``..  |     #
#     .:,,,,,,,,, .'           `. .:,,,,,,,,, |___________ |          ``|     #
#                                                                             #
#                                                                             #
#     Author: Emile Mercier                                                   #
#-----------------------------------------------------------------------------#  

# zazen
#   -p preparation [short|long]
#   -t time in minutes
#   -k kill any running instances of zazen
#
#   sounds are located in /home/kapu/mySounds/zen/undo
#
PROGNAME=$0


finish() {
    rm -f /tmp/zazen_is_running
    rm -f /tmp/zazen_request
    exit
}


usage() {
  cat << EOF >&2
Usage: $PROGNAME [-p <preparation length word>] [-d <duration>]

-p <long|medium|short>: ...
-d <duration in minutes>: ...
EOF
  exit 1
}

trap finish INT
trap finish EXIT

# if there are no args print usage and exit
if [[ $# -eq 0 ]] ; then
    usage
    exit 0
fi

# get state
# is play interval enabled/disabled?
if [[ -f /var/lib/zazen/zazen_interval_boolean ]] ; then
    echo zazen_interval_boolean found
    cat /var/lib/zazen/zazen_interval_boolean | grep -o enabled &&  zazen_interval_boolean=enabled || zazen_interval_boolean=disabled
else
    echo disabled>/var/lib/zazen/zazen_interval_boolean
    zazen_interval_boolean=disabled
fi

prep=none
duration=20
while getopts p:d:k o; do
  case $o in
    (p) prep=$OPTARG;;
    (d) duration=$OPTARG;;
    (k) kill=1;;
    (*) usage
  esac
done
shift "$((OPTIND - 1))"

if [ ! -z "$kill" ];then
while read line;do
kill -9 $line
done << EOF
`cat /tmp/zazen_is_running`
EOF
/home/kapu/bin/coin
exit 0
fi

if [ -e /tmp/zazen_is_running ]; then
  echo zazen is already running...
  exit 1
else
  touch /tmp/zazen_is_running
  echo $$ >> /tmp/zazen_is_running
fi

echo Remaining arguments: "$@"

# ffmpeg -f lavfi -i anullsrc=r=44100:cl=stereo -t 1200 -q:a 9 -acodec libmp3lame out.mp3
if [ "$prep" = short ];then
    prepSound=/home/kapu/mySounds/zen/undo/edited/ready_short.wav
elif [ "$prep" = medium ];then
    prepSound=/home/kapu/mySounds/zen/undo/edited/ready_middle.wav
elif [ "$prep" = long ];then
    prepSound=/home/kapu/mySounds/zen/undo/edited/ready_long.wav
fi

echo $prepSound > /tmp/debug00_prepSound.txt
if [ "$prep" != none ]; then
mplayer "$prepSound"
fi

#mplayer /home/kapu/mySounds/zen/47665__arnaud-coutancier__tibetan-bowl-bol-tibet-attac.wav
startTimestamp=`date +%s`
mplayer -really-quiet -softvol -volume 20 /home/kapu/mySounds/zen/undo/edited/begin_daikei.wav
#mplayer -softvol -volume 110 /home/kapu/mySounds/zen/79119__kabit__bell-nikko.wav

if [[ "foo$zazen_interval_boolean" == fooenabled ]];then
    interval=5 #minutes between intervals
    endtime=$(( $startTimestamp + $(($duration * 60)) ))
    if [ $duration -ge $interval ];then
        while sleep $(($interval * 60));do
            duration=$(($duration - $interval))
            mplayer -really-quiet -softvol -volume 30 /home/kapu/mySounds/zen/PlumVillage_bell.000.wav
            if [ $duration -le $interval ];then # -le so that we don't play interval bell right before end bell
                break
            fi
        done
        while [ `date +%s` -lt $endtime ];do
            sleep 1
        done
    fi
else
    echo sleeping $(($duration * 60)) seconds
    sleep $(($duration * 60))
fi

#mplayer /home/kapu/mySounds/zen/47665__arnaud-coutancier__tibetan-bowl-bol-tibet-attac.wav
#mplayer /home/kapu/mySounds/zen/undo/edited/end_sodo_bell.wav
#mplayer -softvol -volume 110 /home/kapu/mySounds/zen/undo/edited/end_sodo_bell.wav
#mplayer -softvol -volume 110 /home/kapu/mySounds/zen/79119__kabit__bell-nikko_EDIT_lastBell.wav
#mplayer -softvol -volume 110 /home/kapu/mySounds/zen/ShantidevaCenter.wav
#mplayer -softvol -volume 130 /home/kapu/mySounds/zen/PlumVillage.wav
#mplayer -softvol -volume 100 /home/kapu/mySounds/zen/PlumVillage_bell.001.wav
mplayer -softvol -volume 100 /home/kapu/mySounds/zen/390201__ganapataye__02-bells.aiff
#mplayer -softvol -volume 610 /home/kapu/mySounds/zen/zen_flesh_zen_bones.wav
#mplayer -softvol -volume 610 /home/kapu/mySounds/zen/zen_flesh_zen_bones_X2.wav
rm -f /tmp/zazen_request



